### ISSUE TITLE
Error: Cannot find module 'node-extjs-core'

### ISSUE THREAD

**Issue by atian25** [storminwalker/node-extjs#1]
require("node-extjs-core");
console.log(Ext.getVersion().version);

E:\Workspace\Code\PureReader>node app.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'node-extjs-core'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (E:\Workspace\Code\PureReader\app.js:31:1)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)

**Comment by nitingautam** [comment]
is there any updates on this?
